### PR TITLE
Fixed a few bugs in Linux backend

### PR DESCRIPTION
**Pull request by mrmurnst**
Thanks for this very nice library. It saved me from spending hours digging through native code while debugging communications with a device I have here.

After identifying that device's peculiarities, I got it to work on Windows, but stumbled upon a few bugs in the Linux backend.

The commits should be pretty self-explanatory...

### CODE REVIEW

**Comment by nyholku** [comment]
Hi, many thanks for the kind words and contribution. Looks good, I will merger this in a couple of days and make a new release.

**Comment by mrmurnst** [comment]
Hi again, I have added another few commits with fixes for the Windows backend.

## Commit e493298
This is a simple change to have numbered-report-devices behave the same on Windows and Linux. Previously the data array included the report ID for numbered reports on Windows, which is not the case on Linux. I guess your intention was to give the report ID as a separate parameter only.

## Commit 9204e16
This is a workaround for a strange problem. Every other time the WindowsBackend deadlocked on the first call to enumerateDevices. Debugging showed that the DeviceRemovalHandler thread was trying to load some JNA classes at the same time enumerateDevices was loading them, which caused a deadlock in the class loader somehow.

This workaround waits for the DeviceRemovalHandler to have initialized (and thus loaded all necessary classes), before continuing. Maybe there is a better solution, but I am satisfied with this one. ;)

## Commit 0e3b149
A little story behind this change: I have here an RFID reader with a firmware bug. When sending output reports through its interrupt out endpoint, it locks up and doesn't react to any further transmissions. It works when sending output reports over the control endpoint, though.

On Windows one can force reports down the control endpoint even when an interrupt out endpoint exists by using the HidD_SetOutputReport function instead of just writing to the device handle. The code I have added enables/disables this behavior through a system property. Feel free to ignore this commit or solve this somehow differently, if you don't like it.

On Linux a solution to this problem is to use a quirk in the usbhid driver (available since Linux 3.15, [see this](http://lxr.free-electrons.com/diff/drivers/hid/hidraw.c?v=3.14;diffval=3.15;diffvar=v) for the corresponding addition in the kernel code around line 160).

On OS X there is no simple solution as far as I have seen. As I don't own a device running OS X, I haven't investigated very deeply, though...

**Comment by nyholku** [comment]
Looks great. Thank you for taking the trouble to go through the code and fix all these little issues.

I'll look at them in detail tomorrow and will make release, let me know if you think there is more coming so will hold out for a while.

**Comment by nyholku** [comment]
Thanks for the tip, I'll have a look in the morning.

wbr Kusti

**Pull request merged**
