### PR TITLE
Windows HID Device: fixed use of Overlapped I/O

### PR DESCRIPTION
**Pull request by mitza-oci**
Update of #63 and #64, which builds on #54.

### CODE REVIEW

**Comment by nyholku** [comment]
Thanks!

**Comment by nyholku** [comment]
For some reason Merge pull request does nothing ...

**Comment by nyholku** [comment]
Ok, Safari needed updating.

**Comment by mitza-oci** [comment]
Since `bin` of this repository includes the JAR artifacts, we will need to do a follow-up PR to update those.

**Comment by nyholku** [comment]
Feel free.

**Pull request merged**
